### PR TITLE
feat(newlines): Add support for newlines

### PR DESCRIPTION
**Pull request by jeffal**
/cc @wooorm

Re-opening https://github.com/syntax-tree/hast-util-to-mdast/pull/35

Thank you! 😄

### CODE REVIEW

**Comment by wooorm** [comment]
@jeffal 👋

What’s your use case?

**Comment by jeffal** [comment]
I am converting MDAST to HAST, sanitizing, and converting HAST back to MDAST.

**Comment by wooorm** [comment]
Hmm. With what kind of input, output, and expected output?

**Comment by jeffal** [comment]
@wooorm Here are some examples:
screenshot 2018-06-25 12 31 01

**Comment by jeffal** [comment]
@wooorm Does my screenshot answer your question?

There are 4 scenarios:
- Original MDAST input
- Sanitized HAST
- MDAST output
- MDAST output with newlines

**Comment by wooorm** [comment]
Hmm... Sorry about the late response! Extremely busy.
Why would that newline matter in your html though? 🤔

**Comment by jeffal** [comment]
My users are writing Markdown via a `textarea` component. They sometimes include new lines that we would like to preserve following sanitization.

**Pull request closed without merging**
