### PR TITLE
failing paragraph test

### PR DESCRIPTION
**Pull request by sethvincent**
Not sure why yet but this longer paragraph is failing to transform.

Looking into it.

### CODE REVIEW

**Comment by sethvincent** [comment]
nvm, I had a completely different bug going on downstream.

**Comment by wooorm** [comment]
Weird! What’s going on? Also: can this branch be deleted?

**Comment by sethvincent** [comment]
Deleted the branch.

I was working on removing newlines from text in paragraphs (which is something that probably doesn't need to happen in this repo?).

It ended up being pretty easy, I just misunderstood where the error was at first.

**Comment by wooorm** [comment]
Funky! So what’s the error about though?

> I was working on removing newlines from text in paragraphs (which is something that probably doesn't need to happen in this repo?).

Maybe we need to collapse white-space to one space?

**Pull request closed without merging**
