### PR TITLE
Add minify option

### PR DESCRIPTION
**Pull request by erquhart**
Related to https://github.com/wooorm/rehype-minify/issues/19, simply allows minification to be turned off.

### CODE REVIEW

**Comment by wooorm** [comment]
I think this works theoretically (albeit the tests are failing due to coverage not being 100%), but it’ll break a lot in markdown because HTML has insignificant white-space but markdown does not, so if we don’t handle white-space, you’ll see that lots of markdown will be broken, and this utility won’t work anymore! 😬

**Comment by wooorm** [comment]
I didn’t find time to fix this, how are you on this? How’s your work around?

**Comment by wooorm** [comment]
I’m closing this because I (see https://github.com/syntax-tree/hast-util-to-mdast/pull/29#issuecomment-321277588) don’t feel comfortable allowing this. I believe that testing it more will introduce many bugs.

**Comment by erquhart** [comment]
Totally forgot about this, agreed 👍

**Pull request closed without merging**
